spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test_db_for_test_cases?createDatabaseIfNotExist=true
        username: root
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update